### PR TITLE
remove static kernels of pow2

### LINKED ISSUE #67: Problems with double 1D complex interleaved for moderate to large sizes
### What should happen
-rider should run correctly for doubles as well as floats.

### What really happens
-It doesn't, for doubles.  Typically gets output[0].real() = =nan, not N.
As far as I can tell, all sizes > 2048 are broken except for powers of 2.
4096 is also broken, but gets 3.88098e-304 rather than -nan.
8192, 16384, etc. are OK.
 

### How to reproduce
-  ./rocfft-rider --double -o  -p 10 -x 2160

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |
VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/580] (rev e7)
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 1
model name	: AMD Ryzen 7 1800X Eight-Core Processor
stepping	: 1
microcode	: 0x8001129

| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
 4.11.0-kfd-compute-rocm-rel-1.6-180 #1 SMP Tue Oct 10 08:15:38 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux
HCC clang version 6.0.0  (based on HCC 1.0.17412-f590a25-821e6d8-64e7fc7 )
| Library | v0.0 |

### PR DESCRIPTION
**Pull request by tingxingdong**
resolves #67 

Summary of proposed changes:
-  remove expired pow2 kernels and their CPU functions. 
-  the large1D threadhold is stored in radix_table only instead of storing a variable per file.
-  double2 of pow2 split into multiple kernels starting at size 4096 (which is included). 
-  The cpu implementions of kernel_launch_single_large.cpp and kernel_launch_single.cpp are still sperate to speed up compilation. Too many kernels in one file prevent parallel compilation.

### CODE REVIEW

**Comment by bragadeesh** [comment]
This PR still keeps the large 1d threshold as same between single and double; I was clear earlier that this is not what we want. Double max 1d must be half of single max 1d.
Can you rework the code?

**Comment by tingxingdong** [comment]
You mean for pow2 only or for other pow3, 5?

**Comment by bragadeesh** [comment]
What is Large1DThreshold for SP and DP in your code?
Its a common value, applicable to all radices. They don't vary across pow2 pow3 etc,

**Comment by tingxingdong** [comment]
I only maintain one macro 4096.  The double one can be calculated accordingly. 
in plan.cpp 
 
size_t supported[] = {
                  4096, 4050, 4000, 3888, 3840, 3750, 3645, 3600, 3456, 3375, 3240, 3200, 3125, 3072, 3000, 2916, 2880, 2700, 2592, 2560, 2500, 2430, 2400, 2304, 2250, 2187, 2160,		                  4096, 4050, 4000, 3888, 3840, 3750, 3645, 3600, 3456, 3375, 3240, 3200, 3125, 3072, 3000, 2916, 2880, 2700, 2592, 2560, 2500, 2430, 2400, 2304, 2250, 2187, 2160,

If you want to drop pow3, 5 to 2K.  Then do you have to modify this line?

**Comment by tingxingdong** [comment]
see line - 477 in plan.cpp.  if (length[0] > (Large1DThreshold * Large1DThreshold)) 

This is for non-pow2 case, Do you want to add an if-else branch to differentiate SP/DP or not?

**Pull request merged**
