### PR TITLE
create stub folder that contains a minimal example on how to use rocfft

### PR DESCRIPTION
**Pull request by psteinb**
Summary of proposed changes:
-  create a folder `samples` insides the `docs`
-  `samples` contains examples for clients to rocfft (which doesn't depend on boost, fftw, ...)
-  added minimal documentation on how to compile the sample

### CODE REVIEW

**Comment by psteinb** [comment]
I looked at the matter a bit more. with that `install.sh` script in place, it's really hard to find out how rocfft can be used in a client project. As mentioned in the references, I am having a hard time building a client application that uses rocfft. I am currently using rocfft from the rocm 1.9 repos and am not getting anywhere the last 2 days. I'd appreciate any help.

**Comment by bragadeesh** [comment]
Thanks for this contribution, need to look at it
What part are you having trouble with? After you make rocfft package with build (or get it from github or radeon repo) and installed in the system, are you not able to use it?

**Comment by psteinb** [comment]
what I ultimately would want, is a simple cmake snippet or example on how to compile a client to rocfft.

**Comment by psteinb** [comment]
The `install.sh` simply obfuscated to me how I could easily use `rocfft` in my benchmark. CUDA does yield the samples which can provide simple documentation on how to use specific libraries. I simply miss that with rocfft. NB. I am using rocfft from the rocm repos.

**Comment by bragadeesh** [comment]
Understand; is the sample you are contributing now works on your side ok? 
Other than the confusing install.sh, any other issues?

**Comment by psteinb** [comment]
> Understand; is the sample you are contributing now works on your side ok?

yes it does. Would love to see something alike for running on nvidia 
etc. So that people that want to use rocfft, have a clear and easy start 
without the baggage of boost, gtest and fftw.

> Other than the confusing install.sh, any other issues?

Nope, I am in the process of integrating rocfft into 
[gearshifft](https://github.com/mpicbg-scicomp/gearshifft/pull/126)

**Pull request merged**
